-- MÓDULO INDEPENDENTE DE CRM — HUB DE LEADS + FEEDBACK META
-- Banco alvo: Supabase / PostgreSQL.
-- Depende conceitualmente do tracking da migration 004, mas pode evoluir de forma independente.

create extension if not exists pgcrypto;

-- Configuração por cliente. Tokens NÃO devem ser salvos nesta tabela.
create table if not exists public.meta_hub_clientes (
  id uuid primary key default gen_random_uuid(),
  chave_cliente text not null unique,
  nome_cliente text not null,
  ativo boolean not null default true,

  conta_anuncio text,
  dataset_id text,
  graph_api_version text not null default 'v25.0',

  enviar_feedback_meta boolean not null default false,
  sincronizar_publico_qualificados boolean not null default false,
  publico_qualificados_id text,

  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Lead canônico do HUB. O CRM/sistema de origem continua dono do cadastro completo.
create table if not exists public.meta_hub_leads (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.meta_hub_clientes(id) on delete cascade,
  lead_externo_id text not null,
  sistema_origem text not null,
  sessao_id text,
  primeiro_evento_em timestamptz,
  ultimo_evento_em timestamptz,

  -- Identificadores Meta que não são PII bruta.
  meta_lead_id text,
  fbc text,
  fbp text,
  ctwa_clid text,

  -- Atribuição conhecida no primeiro contato.
  conta_anuncio text,
  id_campanha text,
  id_conjunto text,
  id_anuncio text,
  origem_atribuicao text not null default 'desconhecida',
  confianca_atribuicao text not null default 'desconhecida'
    check (confianca_atribuicao in ('alta','media','baixa','desconhecida')),

  -- Gate interno. O cliente/integrador é responsável por informar o uso permitido.
  pode_compartilhar_meta boolean not null default false,
  pode_usar_publico boolean not null default false,

  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),

  unique (cliente_id, lead_externo_id)
);

-- Identificadores de matching armazenados somente em hash SHA-256 quando aplicável.
-- Não guardar e-mail/telefone em texto puro nesta camada.
create table if not exists public.meta_hub_identificadores (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.meta_hub_leads(id) on delete cascade,
  tipo text not null check (tipo in (
    'em','ph','fn','ln','ct','st','zp','country','external_id'
  )),
  valor_hash text not null,
  criado_em timestamptz not null default now(),
  unique (lead_id, tipo, valor_hash)
);

-- Histórico imutável do funil recebido de qualquer sistema.
create table if not exists public.meta_hub_eventos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.meta_hub_clientes(id) on delete cascade,
  lead_id uuid not null references public.meta_hub_leads(id) on delete cascade,
  evento_externo_id text not null,
  evento text not null check (evento in (
    'conversa_iniciada',
    'lead_identificado',
    'lead_qualificado',
    'agendamento',
    'proposta',
    'venda',
    'desqualificado'
  )),
  ocorrido_em timestamptz not null,
  score_qualificacao numeric(8,2),
  valor numeric(14,2),
  moeda text default 'BRL',
  metadata jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  unique (cliente_id, evento_externo_id)
);

-- Mapeamento interno → evento Meta. Permite adaptar por cliente/canal sem alterar código.
create table if not exists public.meta_hub_mapa_eventos_meta (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.meta_hub_clientes(id) on delete cascade,
  evento_interno text not null,
  evento_meta text not null,
  habilitado boolean not null default true,
  prioridade integer not null default 100,
  observacao text,
  unique (cliente_id, evento_interno)
);

-- Outbox para Conversions API. Idempotência impede reenvio lógico do mesmo evento.
create table if not exists public.meta_hub_fila_capi (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.meta_hub_clientes(id) on delete cascade,
  lead_id uuid not null references public.meta_hub_leads(id) on delete cascade,
  evento_id uuid not null references public.meta_hub_eventos(id) on delete cascade,
  event_id text not null unique,
  evento_meta text not null,
  payload jsonb not null,
  status text not null default 'pendente'
    check (status in ('pendente','enviando','enviado','erro','descartado')),
  tentativas integer not null default 0,
  proxima_tentativa_em timestamptz,
  enviado_em timestamptz,
  resposta_meta jsonb,
  ultimo_erro text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Controle de públicos e membros já sincronizados.
create table if not exists public.meta_hub_publicos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references public.meta_hub_clientes(id) on delete cascade,
  tipo text not null check (tipo in ('qualificados','agendados','clientes','desqualificados')),
  nome text not null,
  meta_custom_audience_id text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (cliente_id, tipo)
);

create table if not exists public.meta_hub_publico_membros (
  id bigint generated by default as identity primary key,
  publico_id uuid not null references public.meta_hub_publicos(id) on delete cascade,
  lead_id uuid not null references public.meta_hub_leads(id) on delete cascade,
  status text not null default 'pendente'
    check (status in ('pendente','adicionado','removido','erro','ignorado')),
  hash_enviado text,
  tentativas integer not null default 0,
  sincronizado_em timestamptz,
  ultimo_erro text,
  atualizado_em timestamptz not null default now(),
  unique (publico_id, lead_id)
);

create index if not exists idx_meta_hub_eventos_lead_data
  on public.meta_hub_eventos (lead_id, ocorrido_em desc);

create index if not exists idx_meta_hub_fila_capi_status
  on public.meta_hub_fila_capi (status, proxima_tentativa_em, criado_em);

create index if not exists idx_meta_hub_publico_membros_status
  on public.meta_hub_publico_membros (publico_id, status);

-- Visão operacional por lead.
create or replace view public.v_meta_hub_funil as
select
  l.id as lead_id,
  l.cliente_id,
  l.lead_externo_id,
  l.sistema_origem,
  l.id_campanha,
  l.id_conjunto,
  l.id_anuncio,
  l.origem_atribuicao,
  l.confianca_atribuicao,
  min(e.ocorrido_em) filter (where e.evento = 'lead_identificado') as identificado_em,
  min(e.ocorrido_em) filter (where e.evento = 'lead_qualificado') as qualificado_em,
  min(e.ocorrido_em) filter (where e.evento = 'agendamento') as agendamento_em,
  min(e.ocorrido_em) filter (where e.evento = 'proposta') as proposta_em,
  min(e.ocorrido_em) filter (where e.evento = 'venda') as venda_em,
  max(e.score_qualificacao) as score_qualificacao,
  sum(e.valor) filter (where e.evento = 'venda') as valor_vendas
from public.meta_hub_leads l
left join public.meta_hub_eventos e on e.lead_id = l.id
group by l.id;

alter table public.meta_hub_clientes enable row level security;
alter table public.meta_hub_leads enable row level security;
alter table public.meta_hub_identificadores enable row level security;
alter table public.meta_hub_eventos enable row level security;
alter table public.meta_hub_mapa_eventos_meta enable row level security;
alter table public.meta_hub_fila_capi enable row level security;
alter table public.meta_hub_publicos enable row level security;
alter table public.meta_hub_publico_membros enable row level security;

comment on table public.meta_hub_fila_capi is
'Outbox idempotente para envio de eventos de funil à Meta Conversions API.';

comment on table public.meta_hub_publico_membros is
'Controle de sincronização de leads elegíveis com Custom Audiences da Meta.';
