-- FASE 1 — Base histórica de métricas Meta Ads
-- Banco alvo: Supabase / PostgreSQL.
-- Esta migration apenas define a estrutura. Ela ainda não foi executada em produção.

create table if not exists public.meta_ads_metricas_diarias (
  id bigint generated by default as identity primary key,

  -- Impede que o mesmo objeto seja gravado duas vezes no mesmo dia.
  chave_registro text not null unique,
  data_referencia date not null,
  conta_anuncio text not null,
  nivel_analise text not null check (nivel_analise in ('campanha', 'conjunto', 'anuncio')),

  id_campanha text,
  nome_campanha text,
  objetivo text,
  objetivo_original text,

  id_conjunto text,
  nome_conjunto text,

  id_anuncio text,
  nome_anuncio text,

  investimento numeric(14,2) not null default 0,
  impressoes bigint not null default 0,
  alcance bigint not null default 0,
  cliques bigint not null default 0,
  cliques_link bigint not null default 0,

  leads bigint not null default 0,
  conversas_iniciadas bigint not null default 0,
  primeiras_respostas bigint not null default 0,
  conexoes_mensagem bigint not null default 0,
  visualizacoes_video bigint not null default 0,

  cpc numeric(14,4),
  ctr numeric(14,4),
  cpm numeric(14,4),
  cpl numeric(14,4),
  custo_por_conversa numeric(14,4),

  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Índices usados nas análises por período e por objeto.
create index if not exists idx_meta_ads_metricas_data
  on public.meta_ads_metricas_diarias (data_referencia desc);

create index if not exists idx_meta_ads_metricas_conta_data
  on public.meta_ads_metricas_diarias (conta_anuncio, data_referencia desc);

create index if not exists idx_meta_ads_metricas_campanha
  on public.meta_ads_metricas_diarias (id_campanha, data_referencia desc);

create index if not exists idx_meta_ads_metricas_conjunto
  on public.meta_ads_metricas_diarias (id_conjunto, data_referencia desc)
  where id_conjunto is not null;

create index if not exists idx_meta_ads_metricas_anuncio
  on public.meta_ads_metricas_diarias (id_anuncio, data_referencia desc)
  where id_anuncio is not null;

-- Mantém atualizado_em correto em updates/upserts.
create or replace function public.atualizar_meta_ads_atualizado_em()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_meta_ads_atualizado_em on public.meta_ads_metricas_diarias;

create trigger trg_meta_ads_atualizado_em
before update on public.meta_ads_metricas_diarias
for each row
execute function public.atualizar_meta_ads_atualizado_em();

-- A tabela não deve ficar aberta diretamente para clientes públicos.
alter table public.meta_ads_metricas_diarias enable row level security;

comment on table public.meta_ads_metricas_diarias is
'Histórico diário de métricas Meta Ads por campanha, conjunto e anúncio.';

comment on column public.meta_ads_metricas_diarias.chave_registro is
'Chave no formato data|conta|nivel|id_objeto usada para idempotência.';
