-- MÓDULO DE RASTREAMENTO DE LEADS
-- Banco alvo: Supabase / PostgreSQL.
-- Objetivo: ligar o funil comercial aos IDs de campanha, conjunto e anúncio.
-- Esta migration é de planejamento e ainda não deve ser aplicada sem revisar a integração com o CRM.

create table if not exists public.meta_lead_atribuicao (
  lead_id text primary key,
  sessao_id text,

  conta_anuncio text,
  id_campanha text,
  id_conjunto text,
  id_anuncio text,

  origem_atribuicao text not null default 'desconhecida'
    check (origem_atribuicao in (
      'meta_referral',
      'utm',
      'link_rastreado',
      'formulario_meta',
      'manual',
      'desconhecida'
    )),

  confianca_atribuicao text not null default 'desconhecida'
    check (confianca_atribuicao in ('alta', 'media', 'baixa', 'desconhecida')),

  chave_origem text,
  dados_origem jsonb not null default '{}'::jsonb,

  primeiro_contato timestamptz,
  atribuido_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.meta_lead_eventos (
  id bigint generated by default as identity primary key,
  lead_id text not null references public.meta_lead_atribuicao(lead_id) on delete cascade,

  evento text not null
    check (evento in (
      'conversa_iniciada',
      'lead_identificado',
      'lead_qualificado',
      'agendamento',
      'proposta',
      'venda',
      'desqualificado'
    )),

  ocorrido_em timestamptz not null default now(),
  valor numeric(14,2),
  score_qualificacao numeric(8,2),
  motivo text,
  origem_sistema text,
  dados_evento jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists idx_meta_lead_atribuicao_anuncio
  on public.meta_lead_atribuicao (id_anuncio)
  where id_anuncio is not null;

create index if not exists idx_meta_lead_atribuicao_campanha
  on public.meta_lead_atribuicao (id_campanha)
  where id_campanha is not null;

create index if not exists idx_meta_lead_eventos_lead_data
  on public.meta_lead_eventos (lead_id, ocorrido_em desc);

create index if not exists idx_meta_lead_eventos_evento_data
  on public.meta_lead_eventos (evento, ocorrido_em desc);

create or replace function public.atualizar_meta_lead_atribuicao_em()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_meta_lead_atribuicao_atualizado_em
  on public.meta_lead_atribuicao;

create trigger trg_meta_lead_atribuicao_atualizado_em
before update on public.meta_lead_atribuicao
for each row
execute function public.atualizar_meta_lead_atribuicao_em();

-- Consolida cada lead em uma linha de funil.
create or replace view public.v_meta_lead_funil as
with eventos as (
  select
    lead_id,
    bool_or(evento = 'lead_identificado') as lead_identificado,
    bool_or(evento = 'lead_qualificado') as lead_qualificado,
    bool_or(evento = 'agendamento') as agendamento,
    bool_or(evento = 'proposta') as proposta,
    bool_or(evento = 'venda') as venda,
    bool_or(evento = 'desqualificado') as desqualificado,
    max(score_qualificacao) filter (where evento = 'lead_qualificado') as score_qualificacao,
    max(valor) filter (where evento = 'venda') as valor_venda,
    min(ocorrido_em) filter (where evento = 'lead_qualificado') as qualificado_em,
    min(ocorrido_em) filter (where evento = 'agendamento') as agendado_em,
    min(ocorrido_em) filter (where evento = 'venda') as vendido_em
  from public.meta_lead_eventos
  group by lead_id
)
select
  a.*,
  coalesce(e.lead_identificado, false) as lead_identificado,
  coalesce(e.lead_qualificado, false) as lead_qualificado,
  coalesce(e.agendamento, false) as agendamento,
  coalesce(e.proposta, false) as proposta,
  coalesce(e.venda, false) as venda,
  coalesce(e.desqualificado, false) as desqualificado,
  e.score_qualificacao,
  e.valor_venda,
  e.qualificado_em,
  e.agendado_em,
  e.vendido_em
from public.meta_lead_atribuicao a
left join eventos e using (lead_id);

-- Visão diária que poderá ser unida ao gasto de Meta Ads por data e anúncio.
create or replace view public.v_meta_ads_funil_diario as
select
  timezone('America/Sao_Paulo', primeiro_contato)::date as data_referencia,
  conta_anuncio,
  id_campanha,
  id_conjunto,
  id_anuncio,
  count(*) as leads_atribuidos,
  count(*) filter (where lead_identificado) as leads_identificados,
  count(*) filter (where lead_qualificado) as leads_qualificados,
  count(*) filter (where agendamento) as agendamentos,
  count(*) filter (where proposta) as propostas,
  count(*) filter (where venda) as vendas,
  count(*) filter (where desqualificado) as desqualificados,
  sum(coalesce(valor_venda, 0)) as valor_vendas
from public.v_meta_lead_funil
where primeiro_contato is not null
group by 1, 2, 3, 4, 5;

alter table public.meta_lead_atribuicao enable row level security;
alter table public.meta_lead_eventos enable row level security;

comment on table public.meta_lead_atribuicao is
'Atribuição primária de um lead a campanha, conjunto e anúncio, sem duplicar PII do CRM.';

comment on table public.meta_lead_eventos is
'Histórico de eventos do funil comercial usados para medir qualidade real dos leads.';
