export type EntityStatus = "ACTIVE" | "ARCHIVED";
export type Page<T> = { items: T[]; page: number; page_size: number; total: number; pages: number };
export type Client = { id: string; name: string; slug: string; status: EntityStatus };
export type MetaAccount = { id: string; client_id: string; name: string; currency: string | null; status: EntityStatus; last_synced_at: string | null };
export type Campaign = { id: string; meta_account_id: string; name: string; objective: string | null; status: EntityStatus };
export type Metrics = { spend: number; impressions: number; clicks: number; leads: number; conversations: number; cpl: number | null; ctr: number | null; cpc: number | null; cpm: number | null };
export type Dashboard = {
  clients: number; meta_accounts: number; campaigns: number; adsets: number; ads: number;
  period: { date_from: string; date_to: string; days: number };
  previous_period: { date_from: string; date_to: string; days: number };
  metrics: Metrics; previous_metrics: Metrics; change_percent: Record<keyof Metrics, number | null>;
  daily_series: Array<{ metric_date: string; spend: number; impressions: number; clicks: number; leads: number; conversations: number }>;
  campaign_ranking: Array<{ campaign_id: string; name: string; status: EntityStatus; spend: number; impressions: number; clicks: number; leads: number; conversations: number; cpl: number | null; ctr: number | null; cpc: number | null; cost_per_conversation: number | null }>;
  adset_ranking: EntityPerformance[];
  ad_ranking: EntityPerformance[];
  insights: Array<{ code: string; severity: "INFO" | "WARNING" | "OPPORTUNITY"; title: string; message: string }>;
  recommendations: Recommendation[];
};
export type EntityPerformance = { entity_type: "ADSET" | "AD"; entity_id: string; name: string; status: EntityStatus; spend: number; impressions: number; clicks: number; leads: number; conversations: number; ctr: number | null; cpc: number | null; cost_per_conversation: number | null };
export type Recommendation = { key: string; entity_type: "ADSET" | "AD"; entity_id: string; entity_name: string; rule_code: string; priority: "HIGH" | "MEDIUM" | "LOW"; title: string; explanation: string; evidence: string; expected_impact: string; status: "PENDING" | "ACCEPTED" | "REJECTED" };
export type Improvement = { id: string; title: string; hypothesis: string | null; status: string; metric_name: string | null; before_value: number | null; after_value: number | null; result: string | null; conclusion: string | null; created_at: string };
export type CredentialStatus = { provider: "META_CLIENT" | "META_SYSTEM" | "OPENAI"; configured: boolean; status: string | null; connection_name: string | null; client_id: string | null; config: Record<string, string | null>; last_validated_at: string | null; updated_at: string | null };
export type SettingsData = { system_admin: boolean; credentials: CredentialStatus[] };
